apiVersion: v1
kind: ConfigMap
metadata:
  name: persistencecore
data:
  chain.id: test-core-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firehose-node-config
data:
  sync_node.resolution_method: STATIC
  sync_node.host: ''
  sync_node.exposer_port: ''
  sync_node.port_p2p: '26656'
  sync_node.genesis_json_fetch_url: 'https://raw.githubusercontent.com/persistenceOne/networks/master/test-core-1/final_genesis.json'
  # TODO: change to v6 snapshot
  # snapshot dir structure should follow
  # root
  #   - data
  #     - application.db
  #     - blockstore.db
  #     - ...
  #   - wasm
  snapshot_restore_url: "https://files.audit.one/persistence%2Fsnapshot%2Ftestnet_10192378.tar.lz4"
  seeds: 'b4237f8a7ca357d380ad119b76cbceec7e7e8a75@seed.testnet.persistence.one:26656'
  # For buffer time to sync the node
  first_streamable_block: '10192450'
  force_init: 'false'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-node-config
data:
  #host name format: <Service-namespace-podDNS>
  firehose_node.host: 'persistencecore-firehose-node.graph-test-core-1.svc.cluster.local'
  firehose_node.port: '9030'
  ipfs.host: 'ipfs-node.graph-test-core-1.svc.cluster.local'
  ipfs.port: '5001'