apiVersion: v1
kind: ConfigMap
metadata:
  name: persistencecore
data:
  chain.id: core-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firehose-node-config
data:
  sync_node.resolution_method: STATIC
  sync_node.host: ''
  sync_node.exposer_port: ''
  sync_node.port_p2p: '26656'
  sync_node.genesis_json_fetch_url: 'https://raw.githubusercontent.com/persistenceOne/networks/master/core-1/final_genesis.json'
  snapshot_restore_url: 'https://files.audit.one/persistence%2Fsnapshot%2Fdata_height_10522614.tar.lz4'
  seeds: 'e726816f42831689eab9378d5d577f1d06d25716@persistence-seed-2.allnodes.me:26656,e1b058e5cfa2b836ddaa496b10911da62dcf182e@persistence-seed-1.allnodes.me:26656,fbf0aa94b512902a249b246ed5763b50df9c0543@seed.core.persistence.one:26656'
  first_streamable_block: '10522800'
  force_init: 'false'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-node-config
data:
  firehose_node.host: 'persistencecore-firehose-node.graph-core-1.svc.cluster.local'
  firehose_node.port: '9030'
  ipfs.host: 'ipfs-node.graph-core-1.svc.cluster.local'
  ipfs.port: '5001'