apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firehose-pv-claim
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi