apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: persistencecore-validator
spec:
  serviceName: persistencecore-validator
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: persistencecore
      app.kubernetes.io/name: persistencecore-validator
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: persistencecore
        app.kubernetes.io/type: persistencecore-validator
        app.kubernetes.io/name: persistencecore-validator
        app.kubernetes.io/version: '0.1'
    spec:
      initContainers:
        - name: wait-for-genesis
          image: persistenceone/persistencecore:latest
          imagePullPolicy: Always
          env:
            - name: GENESIS_HOST
              value: persistencecore-genesis.default
            - name: GENESIS_PORT
              value: "8081"
        - name: init-validator
          image: persistenceone/persistencecore:latest
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: persistencecore
            - name: HOME_DIR
              value: /persistencecore
            - name: GENESIS_HOST
              value: persistencecore-genesis.default
            - name: GENESIS_PORT
              value: "8081"
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
          volumeMounts:
            - mountPath: /persistencecore
              name: persistencecore
            - mountPath: /configs
              name: addresses
      containers:
        - name: validator
          image: persistenceone/persistencecore
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "1G"
            requests:
              cpu: "0.1"
              memory: "500M"
        - name: exposer-app
          image: persistenceone/exposer:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
